### ISSUE TITLE
QueryBuilder Search: search by instrumentation needed.

### ISSUE THREAD

**Issue by Alistair-Russell** [Alistair-Russell/mpclOrch#11]
- [x] General instrumentation search.
- [x] Instrumentation search specific to each effect type. (when multiple types are selected revert to general search)
- [x] Need to be able to search for e.g. a Segregation between a flute and an oboe where they are in different groups in the segregation but it doesn't matter which groups.

**Comment by Alistair-Russell** [comment]
General instrument search is fairly straightforward with AND/OR SQ() queries over all instrument many-to-many fields on each effect.
We'll also want to query as eg. "effects where violin is segregating with flute" (where we need multiple queries to check that they are in segregation groups but not in the same one) or eg."instrumentX in foreground while instrumentY in middleground" (where we need to check all middleground fields for instrumentY).

Possible instrumentation queries: "general (AND/OR)", "instrument_listX segregating/contrasting with instrument_listY", "dominating/embellishing" (could make these separate), "foreground/middleground/background" (could make these separate).

**Comment by ahankinson** [comment]
Is this in the database or in solr?

**Comment by Alistair-Russell** [comment]
@ahankinson I'm using haystack's SQ() objects with the querybuilder so this would be in Solr. There are just many ways we would like to query the instrument many-to-many fields. Some effects have multiple m2m fields too.

**Comment by Alistair-Russell** [comment]
Are you thinking I should use copyfields to simplify cases where I need to query multiple instrument fields?
