### ISSUE TITLE
Serialization: List views load time

### ISSUE THREAD

**Issue by Alistair-Russell** [Alistair-Russell/mpclOrch#6]
The time it takes for the list views to load is long due to unneeded serialization.
Introduce custom list serializers.

**Comment by ahankinson** [comment]
It could also be too many SQL calls. Are you using the Django Debug Toolbar? You can see how many SQL calls go into making a request. If you use `select_related` you can sometimes reduce this pretty drastically -- I once reduced a single page load from 2200 to 11 SQL calls just using `select_related`.

**Comment by Alistair-Russell** [comment]
@ahankinson Thanks! I'll take a look into that, I remember coming across that before somewhere. I'm not using Django Debug Toolbar but I just checked it out and it's perfect for what I'm doing now.

**Comment by Alistair-Russell** [comment]
Wow, after testing with select_related and prefetch_related it went from ~100 SQL calls to 4 SQL calls per page... Thanks! this was really helpful

**Comment by ahankinson** [comment]
Nice❗
